import Head from 'next/head'
import BuildUp from '../components/build-up'
import BulletPoints from '../components/bullet-points'
import BusProb from '../components/bus-prob'
import BusSol from '../components/bus-sol'
import Intro from '../components/intro'
import Offer from '../components/offer'
import Perso from '../components/perso'
import Portfolio from '../components/portfolio'
import Prog from '../components/prog'
import Prog2 from '../components/prog-2'
import Prog3 from '../components/prog-3'
import Rocket from '../components/rocket'
import BulletPoints2 from '../components/stats'
import Go from '../components/go'
import Chat from '../components/chat'
import Footer from '../components/footer'


// const Chat = dynamic(
//   () => {
//     Kommunicate.init("1dee383a46e76662a7bcd71893d984010" , {"popupWidget":true,"automaticChatOpenOnNavigation":true})
// }, 
//   {ssr: false}
// );


export default function Home() {
  return (
    <div className='scroll-smooth'>
      <Head>
        <title>Formation développeur web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro />
      <BusProb />
      <BuildUp />
      <BusSol />
      <Portfolio />
      <BulletPoints />
      <Prog />
      <Prog2 />
      <Prog3 />
      <BulletPoints2 />
      <Perso />
      <Rocket />
      <Offer />
      <Go />
      <Footer />
      <Chat />

    </div>
  )
}
